baseURL: "https://portfolio-89m.pages.dev/"
languageCode: en-us
title: Tanzeel
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: experience
      name: Experience
      url: /experience
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: Case Study
      name: Case Study
      url: /case study
      weight: 40
    - identifier: blog
      name: Blog
      url: /blog
      weight: 50
    - identifier: search
      name: Search
      url: /search
      weight: 60
    - identifier: tags
      name: Tags
      url: /tags
      weight: 70
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Tanzeel"
    subtitle: Hi 👋! I'm Tanzeel.I bring a solid foundation in Software Engineering with professional experience. I have deep fascination for the captivating worlds of **User Experience (UX)** and **front-end development**. The ever-evolving tech landscape inspires me to explore innovative ways to engage users, enhance accessibility, and elevate digital interfaces to the next level. During my leisure hours, I love learning about new developments taking place in the field of Science and Technology through books, articles and video platforms like youtube. Other areas which interest me include Pyshcology and Philosophy.
    imageUrl: "home/coding-freak.gif"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:tanzeel.ahmed1306@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/tanzeel-ahmed-shaikh-1b633b12b/"
    - name: "github"
      url: "https://github.com/Tanzeel159"
    - name: "Behance"
      url: "https://www.behance.net/tanzeelahmed11"
    - name: "Dribble"
      url: "https://dribbble.com/Tanzeel098"
    - name: "Codepen"
      url: "https://codepen.io/tanzeel098"
    - name: "CV"
      url: "https://drive.google.com/file/d/12b9pOJVfSqwMQWA42gW5osuWb4ONxsUc/view?usp=drive_link"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
